# Generated by Django 5.2.3 on 2025-06-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='song',
            name='decade',
            field=models.CharField(choices=[('70s', '70s'), ('80s', '80s'), ('90s', '90s'), ('00s', '00s'), ('10s', '10s'), ('20s', '20s')], default='20s', max_length=3),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Disco', 'Disco'), ('New Wave', 'New Wave'), ('Hip Hop', 'Hip Hop'), ('Electronic', 'Electronic'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Country', 'Country'), ('R&B', 'R&B')], default='Pop', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'genre')},
        ),
    ]
