# Generated by Django 5.2.3 on 2025-06-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_options_song_decade_song_genre_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'artist'), ('title', 'decade')},
        ),
    ]
