# Generated by Django 5.2.3 on 2025-06-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
    ]
