# Generated by Django 5.2.3 on 2025-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_art_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
