# Generated by Django 5.2.3 on 2025-06-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_cover_art_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'album'), ('title', 'artist')},
        ),
    ]
