# Generated by Django 5.0.1 on 2025-06-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_song_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'artist')},
        ),
    ]
