# Generated by Django 5.0.1 on 2025-06-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_update_unique_constraints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'album'), ('title', 'artist')},
        ),
    ]
